version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
    - "skip-release-notes"
    - "dependencies"
  - package-ecosystem: "npm"
    directory: "userdocs/profiles.dev"
    schedule:
      interval: "weekly"
    labels:
    - "skip-release-notes"
    - "dependencies"
