apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: catalog-service
  namespace: profiles-system
spec:
  ports:
  - name: http
    port: 8000
  selector:
    control-plane: controller-manager
