# permissions for end users to view profileinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profileinstallation-viewer-role
rules:
- apiGroups:
  - weave.works
  resources:
  - profileinstallations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weave.works
  resources:
  - profileinstallations/status
  verbs:
  - get
