# permissions for end users to edit profilesubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profilesubscription-editor-role
rules:
- apiGroups:
  - weave.works
  resources:
  - profilesubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weave.works
  resources:
  - profilesubscriptions/status
  verbs:
  - get
