# permissions for end users to edit profileinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profileinstallation-editor-role
rules:
- apiGroups:
  - weave.works
  resources:
  - profileinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weave.works
  resources:
  - profileinstallations/status
  verbs:
  - get
