# permissions for end users to view profilesubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profilesubscription-viewer-role
rules:
- apiGroups:
  - weave.works
  resources:
  - profilesubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weave.works
  resources:
  - profilesubscriptions/status
  verbs:
  - get
