apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: nginx-profile-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/profiles-examples
  version: weaveworks-nginx/v0.1.0
  values:
    replicaCount: 3
    service:
      port: 8081
